### ISSUE TITLE
Please add support to ignore files based on names

### ISSUE THREAD

**Issue by justrajdeep** [ckarnell/history-traverse#11]
Hi 

This is an enhancement request to add support to ignore files based on names along with filetypes.

Thanks in advance :)
Rajdeep

**Comment by ckarnell** [comment]
This shouldn't be too hard to add, I'll look into it this weekend. Thanks for the request!

**Comment by justrajdeep** [comment]
Thank you :)

**Comment by ckarnell** [comment]
Added! The config option is called g:history_fn_ignore (check the README for usage). Thanks for the suggestion, let me know if you have any issues.

**Comment by justrajdeep** [comment]
Fixed in dfc8a4e18d49547b9a87688222a32019d2a83dcb

Thanks
